import type { Metadata } from "next";
import { Inter } from "next/font/google"; // Import Inter font
import "./globals.css";
import { AuthProvider } from '@/contexts/AuthContext';

const inter = Inter({ // Define Inter font
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={`${inter.variable} font-sans antialiased`}> {/* Apply Inter font */}
        <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
