-- Enhance security policies for profile pictures

-- Update storage policies with more specific security rules
CREATE OR REPLACE FUNCTION is_profile_owner()
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  RETURN (SELECT auth.uid() = owner FROM storage.objects WHERE id = (SELECT id FROM storage.objects WHERE bucket_id = 'profile-pictures' LIMIT 1));
END;
$$;

-- Update the storage policies for more granular control
-- For INSERT operations, we only check that the user is authenticated and the filename format is correct
-- The owner field is automatically set by Supabase after successful authentication
DROP POLICY IF EXISTS "Users can upload profile pictures" ON storage.objects;
CREATE POLICY "Users can upload profile pictures" ON storage.objects FOR INSERT
 WITH CHECK (
    bucket_id = 'profile-pictures'
    AND auth.role() = 'authenticated'
    -- Ensure the file path starts with the user's ID
    AND (storage.objects.name ILIKE CONCAT(auth.uid(), '/%'))
  );

-- For UPDATE operations, we check that the user is the owner of the file
DROP POLICY IF EXISTS "Users can update own profile pictures" ON storage.objects;
CREATE POLICY "Users can update own profile pictures" ON storage.objects FOR UPDATE
 USING (
    bucket_id = 'profile-pictures'
    AND auth.uid() = owner
  );

-- For DELETE operations, we check that the user is the owner of the file
DROP POLICY IF EXISTS "Users can delete own profile pictures" ON storage.objects;
CREATE POLICY "Users can delete own profile pictures" ON storage.objects FOR DELETE
 USING (
    bucket_id = 'profile-pictures'
    AND auth.uid() = owner
 );

-- Enhanced function to validate profile picture updates
CREATE OR REPLACE FUNCTION validate_profile_picture_update(user_id UUID, new_filename TEXT)
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
 existing_filename TEXT;
BEGIN
  -- Check if the user is authenticated and matches the requested user_id
  IF auth.uid() != user_id THEN
    RETURN FALSE;
  END IF;

  -- Verify the filename format (should be user_id/timestamp_filename.ext)
  IF new_filename NOT ILIKE CONCAT(user_id, '/%') THEN
    RETURN FALSE;
  END IF;

  RETURN TRUE;
END;
$$;

-- Remove the trigger function as RLS policies provide sufficient validation
DROP TRIGGER IF EXISTS validate_profile_picture_upload_trigger ON storage.objects;
DROP FUNCTION IF EXISTS validate_profile_picture_upload();

-- Update the update_profile_picture_metadata function to include validation
-- The avatar_url should be passed in as a parameter since it's generated by the application
CREATE OR REPLACE FUNCTION update_profile_picture_metadata(user_id UUID, avatar_url_param TEXT, filename TEXT, file_size INTEGER, file_type TEXT)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
 -- Validate that the user is authenticated and matches the target user_id
  IF auth.uid() != user_id THEN
    RAISE EXCEPTION 'Unauthorized: Cannot update profile picture for another user';
  END IF;

 -- Validate filename format
 IF filename NOT ILIKE CONCAT(user_id, '/%') THEN
    RAISE EXCEPTION 'Invalid filename format';
  END IF;

 -- Validate file type
 IF file_type NOT IN ('image/jpeg', 'image/jpg', 'image/png', 'image/gif', 'image/webp') THEN
    RAISE EXCEPTION 'Invalid file type';
  END IF;

 -- Validate file size (max 5MB)
  IF file_size > 5242880 THEN
    RAISE EXCEPTION 'File size exceeds 5MB limit';
  END IF;

  UPDATE public.users
  SET
    avatar_url = avatar_url_param,
    profile_image_filename = filename,
    profile_image_size = file_size,
    profile_image_type = file_type,
    profile_image_updated_at = NOW()
  WHERE id = user_id;
END;
$$;

-- Also update the function in the 02_profile_pictures_schema.sql file to remove the reference to app.supabase_base_url which might not be set
-- This function should be in the 02 schema file, so let's update the function that's in this file to remove the dependency on app.supabase_base_url